### ISSUE TITLE
Peering Filter Does Not Work

### ISSUE THREAD

**Issue by aetherrealm** [nautobot/nautobot-plugin-bgp-models#112]
### Environment
* Python version:  3.8.1
* Nautobot version:  1.5.22
* nautobot-bgp-models version:  0.7.0b10

### Expected Behavior
Ability to filter BGP peerings by peering role.

### Observed Behavior
When applying the role filter (drop down is properly populated) in the "Peerings" menu in the Routing plugin tab, the following error is thrown:
Invalid filters were specified:
role
Unknown filter field

As a side note, the role is also not visible / configurable column in the table either.

**Comment by mzbroch** [comment]
Indeed, we decided not to define the "role" on the Peering itself, but rather on the PeerEndpoint.
This would allow to define role as it is in reality, ie:
a) PeerA - customer
b) PeerB - ISP, provider

etc.

If this is Your modelling use-case, I think we analyse if adding a Filter on Peering to loosely match on any of the Peering's endpoints would be feasible.

**Comment by aetherrealm** [comment]
That's an interesting point-- I've never considered any peering a separate 'thing' on either end. If I have a BGP peering with a provider, that's just a provider peering from the customers prospective, we would never separately call out our end of the peering. Our model is built on this notion because, for example, our inter domain BGP peerings are both 'inter-domain' on either end. Leaf to spine is simply 'leaf-spine', and so on. If that filter option that currently is visible in the filter drop down worked, it would allow us to filter down to all similar peerings.

From your perspective I think the loose match would work, and possibly if you allowed compound filtering that field like 'inter-domain' OR 'leaf-spine' (or an AND) which would allow folks who actually have either end labeled differently to filter down to the ones they know match those 2 conditions.

Either way, the filter doesn't currently work on the peerings page even though it's a selectable option. Thank you!

**Comment by mzbroch** [comment]
> From your perspective I think the loose match would work, and possibly if you allowed compound filtering that field like 'inter-domain' OR 'leaf-spine' (or an AND) which would allow folks who actually have either end labeled differently to filter down to the ones they know match those 2 conditions.

We considered more use cases, and decided to define role on the `PeerEndpoint`. This allows us to support more scenarios, including transit routers, where some of the peers have `role=provider`, some others have `role=customer` and some other have `role=internal` (under single `^router bgp 123` process.

I think the way we could design a "peering filter" would be following:

```
PeeringFilter (2 fields) :
 - peer_a_role (OR)
 - peer_b_role (OR)
```

If both `peer_a_role` and `peer_b_role` are defined that would result in `AND` between them.
If only `peer_a_role` (OR) is defined, that would match any of the peers (a or b) side as we don't index peers in the Peering.

@glennmatthews What are Your thoughts ? Is this something we could implement considering technical solution ?

**Comment by glennmatthews** [comment]
Sounds a bit complicated to me but maybe there's a use case for it. My naive approach would be to simply have a single `peer_role` filter that matches either side, similar to the core `CableFilterSet.device` filter. *Maybe* if there's a strong need for it, have also a `peer_roles` filter that takes two inputs and matches either/both endpoints together. I think that'd probably be cleaner than having a filter that acts differently depending on whether another filter is used in combination with it.

**Comment by mzbroch** [comment]
@aetherrealm I believe this should fix your case :

<img width="463" alt="Screenshot 2023-07-24 at 13 38 59" src="https://github.com/nautobot/nautobot-plugin-bgp-models/assets/16935122/37546cbc-a76c-472e-9077-bbe25e192a6d">

This would allow You to filter peerings based on Device Name, Device Role name and Peer Endpoint Role.
This would match on any endpoint side.

**Comment by mzbroch** [comment]
@aetherrealm Is your use case is now possible with the proposed solution ?
